
services:
  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-1
    hostname: kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=9rN8Gv3gRTa9JFYuCq9ZUw
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka-1:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./kafka/kafka_1:/bitnami/kafka

  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-2
    hostname: kafka-2
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=9rN8Gv3gRTa9JFYuCq9ZUw
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka-2:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./kafka/kafka_2:/bitnami/kafka

  kafka-3:
    image: bitnami/kafka:latest
    container_name: kafka-3
    hostname: kafka-3
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=9rN8Gv3gRTa9JFYuCq9ZUw
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false 
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka-3:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./kafka/kafka_3:/bitnami/kafka

  init-topic:
    build: ./init-topic
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/topic-created ]"]
      interval: 5s
      timeout: 3s
      retries: 5


  # PRODUCTEURS
  producer-paris:
    build: ./producer
    environment:
      VILLE: "paris"
      INTERVAL: "1"
      BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      KAFKA_HOST: "kafka-1"
      KAFKA_PORT: "9092"
      TOPIC_NAME: "weather"



  # CONSOMMATEURS
  consumer-paris:
    build: ./consumer
    environment:
      VILLE: "paris"
      INTERVAL: "1"
      BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      KAFKA_HOST: "kafka-1"
      KAFKA_PORT: "9092"
      TOPIC_NAME: "weather"
      GROUP_ID: "consumer-paris"


  # UI KAFDROP
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka-1:9092
    depends_on:
      kafka-1:
        condition: service_healthy

