version: '3.8'
services:
  kafka-4:
    image: bitnami/kafka:latest
    container_name: kafka-4
    hostname: kafka-4
    ports:
      - "9404:9092"
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=9rN8Gv3gRTa9JFYuCq9ZUZw
      - KAFKA_CFG_NODE_ID=4
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=4@kafka-4:9093,5@kafka-5:9093,6@kafka-6:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-4:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
#      - KAFKA_LOG_FLUSH_INTERVAL_MS=1000
#      - KAFKA_LOG_FLUSH_INTERVAL_BYTES=41943040

    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka-4:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-5:
    image: bitnami/kafka:latest
    container_name: kafka-5
    hostname: kafka-5
    ports:
      - "9505:9092"
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=9rN8Gv3gRTa9JFYuCq9ZUZw
      - KAFKA_CFG_NODE_ID=5
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=4@kafka-4:9093,5@kafka-5:9093,6@kafka-6:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-5:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
#      - KAFKA_LOG_FLUSH_INTERVAL_MS=1000
#      - KAFKA_LOG_FLUSH_INTERVAL_BYTES=41943040
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka-5:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka-6:
    image: bitnami/kafka:latest
    container_name: kafka-6
    hostname: kafka-6
    ports:
      - "9606:9092"
    environment:
      - KAFKA_KRAFT_CLUSTER_ID=9rN8Gv3gRTa9JFYuCq9ZUZw
      - KAFKA_CFG_NODE_ID=6
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=4@kafka-4:9093,5@kafka-5:9093,6@kafka-6:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-6:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_DELETE_TOPIC_ENABLE=true
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
#      - KAFKA_LOG_FLUSH_INTERVAL_MS=1000
#      - KAFKA_LOG_FLUSH_INTERVAL_BYTES=41943040
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka-6:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

 